package MessengerApp.MessengerPackage;


/**
* MessengerApp/MessengerPackage/messagesHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Messenger.idl
* mardi 20 décembre 2016 15 h 09 CET
*/

public final class messagesHolder implements org.omg.CORBA.portable.Streamable
{
  public MessengerApp.Message value[] = null;

  public messagesHolder ()
  {
  }

  public messagesHolder (MessengerApp.Message[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = MessengerApp.MessengerPackage.messagesHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    MessengerApp.MessengerPackage.messagesHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return MessengerApp.MessengerPackage.messagesHelper.type ();
  }

}
