package MessengerApp;

/**
* MessengerApp/MessengerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Messenger.idl
* mardi 20 décembre 2016 15 h 09 CET
*/

public final class MessengerHolder implements org.omg.CORBA.portable.Streamable
{
  public MessengerApp.Messenger value = null;

  public MessengerHolder ()
  {
  }

  public MessengerHolder (MessengerApp.Messenger initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = MessengerApp.MessengerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    MessengerApp.MessengerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return MessengerApp.MessengerHelper.type ();
  }

}
